name: 'Smoke test'
description: 'Smoke test for templates'
inputs:
  template:
    description: 'Template to test'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v4

    - name: List current Dir
      shell: sh
      run: |
        pwd
        ls -lah
        echo GITHUB_ACTION_PATH=${{ github.action_path }}
        echo -e "ENV:\n\n\n"
        printenv

    - name: Build template
      id: build_template
      shell: sh
      run: ${{ github.actions }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: sh
      run: ${{ github.actions}}/test.sh  ${{ inputs.template }}